---
kind: pipeline
type: docker
name: build-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: docker
    image: registry.slr.ovh/drone-docker
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    settings:
      repo: registry.slr.ovh/rpi-node-puppeteer
      registry: registry.slr.ovh
      tags:
        - linux-arm64
      dry-run: true
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
  - name: Run test
    image: registry.slr.ovh/rpi-node-puppeteer:linux-arm64
    commands: 
      - npm install
      - npm test

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

image_pull_secrets:
  - docker_config

---
kind: pipeline
type: docker
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: registry.slr.ovh/drone-docker
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    settings:
      repo: registry.slr.ovh/rpi-node-puppeteer
      registry: registry.slr.ovh
      tags:
        - linux-amd64
      dry-run: true
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
  - name: Run test
    image: registry.slr.ovh/rpi-node-puppeteer:linux-amd64
    commands: 
      - npm install
      - npm test

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

image_pull_secrets:
  - docker_config
